[package]
name = "application"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infrastructure = { path = "../infrastructure" }
shared = { path = "../shared" }

dotenv = "0.15.0"

cln-rpc = "0.1.6"
anyhow = "1.0"
bitcoin = { version = "0.30.1", features = [ "serde" ] }
bytes = "1"
futures-util = { version = "0.3", features = [ "sink" ] }
hex = "0.4.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
tokio = { version = "1", features = ["full"]}
tokio-util = { version = "0.7", features = ["codec"] }

simple-home-dir = "0.2.0"
rand = "0.8.5"
easy-hasher = "2.2.1"

[dev-dependencies]
env_logger = "0.10"
tokio = { version = "1", features = ["net", "macros", "rt-multi-thread"]}
