[debug]
address = "127.0.0.1"
port = 3005
keep_alive = 5
log_level = "debug"
limits = { forms = 32768 }

[release]
address = "127.0.0.1"
port = 3005
keep_alive = 5
log_level= "debug"
limits = { forms = 32768 }