[node]
macaroon_file = "admin.macaroon"
cert_file = "tls.cert"
host = "127.0.0.1"
port = 8080
expiry = 3600
cltv_expiry = 80
max_paths = 5 
pathfinding_timeout = 60  
max_fee = 0.01
min_fee = 5
out = "xxx"

[server]
database_url = "postgres://USER:PASSWORD@SERVER:PORT/lightningapi?sslmode=disable"
host = "127.0.0.1"
port = "8181"

[log]
level = "info"

[app]
image_url = "https://"

[openapi]
swagger = false

[api]
api_server= "https://"
api_user= ""
api_pass= ""

[jwt]
jwt_secret= "SECRET"
jwt_secs= 3600 

[job]
seconds= 60